import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  apiSidebar: [
    'index',
    'reference',
    { type: 'autogenerated', dirName: 'generated' },
  ],
};

export default sidebars;
