// <auto-generated />
// HNFixedPoint — 定点数类型别名
// 映射到 FixedMathSharp.Fixed64（Core/Vendor 引入）
// 保持与原先 HNFixedPoint 命名意图的兼容性

using FixedMathSharp;

namespace HN.Framework.Core.Driver.Common.Math
{
    /// <summary>
    /// <see cref="HNFixedPoint"/> 是 <see cref="Fixed64"/> 的类型别名，
    /// 提供与自研定点数方案兼容的命名。
    /// </summary>
    /// <remarks>
    /// 实际实现委托给 <see cref="FixedMathSharp.Fixed64"/>（Core/Vendor 引入的 Lean 版 FixedMathSharp）。
    /// 所有定点数运算通过 <see cref="Fixed64"/> 的公共 API 完成。
    /// </remarks>
    public readonly struct HNFixedPoint
    {
        /// <summary>
        /// 内部持有的 <see cref="Fixed64"/> 值。
        /// </summary>
        public readonly Fixed64 Value;

        /// <summary>
        /// 使用 <see cref="Fixed64"/> 构造 <see cref="HNFixedPoint"/>。
        /// </summary>
        public HNFixedPoint(Fixed64 value) => Value = value;

        /// <summary>
        /// 从原始长整型值构造。
        /// </summary>
        public static HNFixedPoint FromRaw(long raw) => new HNFixedPoint(new Fixed64(raw));

        /// <summary>
        /// 获取原始长整型值。
        /// </summary>
        public long RawValue => Value.m_rawValue;

        /// <summary>
        /// 从 <see cref="Fixed64"/> 隐式转换到 <see cref="HNFixedPoint"/>。
        /// </summary>
        public static implicit operator HNFixedPoint(Fixed64 value) => new HNFixedPoint(value);

        /// <summary>
        /// 从 <see cref="HNFixedPoint"/> 隐式转换到 <see cref="Fixed64"/>。
        /// </summary>
        public static implicit operator Fixed64(HNFixedPoint value) => value.Value;

        /// <inheritdoc />
        public override string ToString() => Value.ToString();
    }
}
